spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/football-platform?currentSchema=football_platform&useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:netopia}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:create}
      show-sql: ${JPA_SHOW_SQL:false}
      properties:
        hibernate:
          dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
          format_sql: ${HIBERNATE_FORMAT_SQL:true}
    open-in-view: ${JPA_OPEN_IN_VIEW:false}